import os


HOST = os.getenv("DREAMGRID_ANALYSIS_HOST", "0.0.0.0")
PORT = int(os.getenv("DREAMGRID_ANALYSIS_PORT", "5005"))
ANALYSIS_BACKEND = os.getenv("DREAMGRID_ANALYSIS_BACKEND", "rule-based")
MODEL_NAME = os.getenv("DREAMGRID_ANALYSIS_MODEL", "google/flan-t5-small")
DEFAULT_MODEL_VERSION = MODEL_NAME if ANALYSIS_BACKEND == "transformers" else ANALYSIS_BACKEND
MODEL_VERSION = os.getenv("DREAMGRID_ANALYSIS_VERSION", DEFAULT_MODEL_VERSION)
MAX_INPUT_LENGTH = int(os.getenv("DREAMGRID_ANALYSIS_MAX_INPUT_LENGTH", "512"))
MAX_OUTPUT_LENGTH = int(os.getenv("DREAMGRID_ANALYSIS_MAX_OUTPUT_LENGTH", "256"))
REQUEST_TIMEOUT_SECONDS = int(os.getenv("DREAMGRID_ANALYSIS_TIMEOUT_SECONDS", "30"))
DEVELOPMENT_MODE = os.getenv("DREAMGRID_ANALYSIS_DEVELOPMENT_MODE", "false").lower() == "true"
HUGGINGFACE_TOKEN = os.getenv("HUGGINGFACE_TOKEN")
