import os


HOST = os.getenv("DREAMGRID_ANALYSIS_HOST", "0.0.0.0")
PORT = int(os.getenv("DREAMGRID_ANALYSIS_PORT", "5005"))
MODEL_NAME = os.getenv("DREAMGRID_ANALYSIS_MODEL", "google/flan-t5-small")
MODEL_VERSION = os.getenv("DREAMGRID_ANALYSIS_VERSION", MODEL_NAME)
MAX_INPUT_LENGTH = int(os.getenv("DREAMGRID_ANALYSIS_MAX_INPUT_LENGTH", "512"))
MAX_OUTPUT_LENGTH = int(os.getenv("DREAMGRID_ANALYSIS_MAX_OUTPUT_LENGTH", "256"))
REQUEST_TIMEOUT_SECONDS = int(os.getenv("DREAMGRID_ANALYSIS_TIMEOUT_SECONDS", "30"))
DEVELOPMENT_MODE = os.getenv("DREAMGRID_ANALYSIS_DEVELOPMENT_MODE", "false").lower() == "true"
HUGGINGFACE_TOKEN = os.getenv("HUGGINGFACE_TOKEN")
