import os


HOST = os.getenv("DREAMGRID_ANALYSIS_HOST", "0.0.0.0")
PORT = int(os.getenv("DREAMGRID_ANALYSIS_PORT", "5005"))
MODEL_NAME = os.getenv("DREAMGRID_ANALYSIS_MODEL", "google/flan-t5-small")
MODEL_VERSION = os.getenv("DREAMGRID_ANALYSIS_VERSION", "v1")
MAX_INPUT_LENGTH = int(os.getenv("DREAMGRID_ANALYSIS_MAX_INPUT_LENGTH", "512"))
MAX_OUTPUT_LENGTH = int(os.getenv("DREAMGRID_ANALYSIS_MAX_OUTPUT_LENGTH", "256"))
HUGGINGFACE_TOKEN = os.getenv("HUGGINGFACE_TOKEN")
